# Generated by Django 5.2.8 on 2025-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(help_text="Internal customer identifier (e.g., 'cust-1001').", max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name of the customer.', max_length=255, unique=True)),
                ('external_ref', models.CharField(blank=True, help_text='Optional CRM / billing reference (e.g., Stripe or HubSpot ID).', max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for licensing notifications.', max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person.', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Free-form notes about contract terms, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
