# Generated by Django 5.2.8 on 2025-11-17 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.CharField(help_text='Internal DB identifier for the license record.', max_length=64, primary_key=True, serialize=False)),
                ('license_id', models.CharField(help_text='License identifier as appears in payload (typically a UUID).', max_length=128, unique=True)),
                ('license_type', models.CharField(help_text='trial | subscription | perpetual', max_length=32)),
                ('valid_from', models.DateTimeField(help_text='UTC datetime from which this license is considered valid.')),
                ('valid_until', models.DateTimeField(help_text='UTC datetime after which this license is considered expired.')),
                ('meta_version', models.IntegerField(default=1, help_text='Version of the license meta format.')),
                ('meta_alg', models.CharField(default='Ed25519', help_text='Signature algorithm used to sign the payload.', max_length=32)),
                ('meta_key_id', models.CharField(help_text='Refers to KeyMetadata.key_id used for signing.', max_length=64)),
                ('payload', models.JSONField(help_text='Canonical payload object used for signing.')),
                ('signature', models.TextField(help_text='Base64-url encoded signature over the canonical payload.')),
                ('issued_at', models.DateTimeField(help_text='UTC timestamp from payload.issuer.issued_at.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('superseded', 'Superseded'), ('expired', 'Expired (record only)')], default='active', help_text='Admin-visible logical status; offline clients ignore this.', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about revocation, contract terms, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='customers.customer')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='products.edition')),
                ('issued_by', models.ForeignKey(help_text='Admin/operator user who issued this license.', on_delete=django.db.models.deletion.PROTECT, related_name='issued_licenses', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseTemplate',
            fields=[
                ('id', models.CharField(help_text="Internal template identifier (e.g., 'tmpl-ent-annual').", max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable template name (e.g., 'Enterprise Annual Default').", max_length=255, unique=True)),
                ('license_type', models.CharField(choices=[('trial', 'Trial'), ('subscription', 'Subscription'), ('perpetual', 'Perpetual')], help_text='Default license type for this template.', max_length=32)),
                ('duration_days', models.IntegerField(blank=True, help_text='Default duration in days (e.g., 14 for trials). Optional.', null=True)),
                ('default_features', models.JSONField(blank=True, help_text='Default features object to merge into payload.features.', null=True)),
                ('default_usage_limits', models.JSONField(blank=True, help_text='Default usage_limits object to merge into payload.usage_limits.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about when/how to use this template.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_templates', to='products.edition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_templates', to='products.product')),
            ],
            options={
                'ordering': ['product__code', 'edition__code', 'name'],
            },
        ),
    ]
