# Generated by Django 5.2.8 on 2025-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMetadata',
            fields=[
                ('id', models.CharField(help_text="Internal key metadata ID (e.g., 'key-main-v1').", max_length=64, primary_key=True, serialize=False)),
                ('key_id', models.CharField(help_text="Key identifier used in license meta.key_id (e.g., 'main-v1').", max_length=64, unique=True)),
                ('alg', models.CharField(help_text="Signature algorithm (e.g., 'Ed25519').", max_length=32)),
                ('description', models.TextField(blank=True, help_text='Optional description of where/how this key is used.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key should be used for issuing new licenses.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Timestamp when key stopped being used for new licenses.', null=True)),
            ],
            options={
                'ordering': ['key_id'],
            },
        ),
    ]
