# Generated by Django 5.2.8 on 2025-11-17 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(help_text="Internal product identifier (e.g., 'prod-data-pipeline').", max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Short code used in license payload (e.g., 'data-pipeline-app').", max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable product name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the product.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is currently sold/licensed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.CharField(help_text="Internal feature identifier (e.g., 'feat-adv-export').", max_length=64, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Feature key used in license payload (e.g., 'advanced_export').", max_length=128)),
                ('name', models.CharField(help_text='Human-readable feature name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this feature enables.', null=True)),
                ('feature_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer_limit', 'Integer limit'), ('string', 'String'), ('json', 'JSON')], default='boolean', max_length=32)),
                ('default_value', models.JSONField(blank=True, help_text='Optional default value if not explicitly set in license.', null=True)),
                ('is_deprecated', models.BooleanField(default=False, help_text='Mark true when this feature is no longer used.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'ordering': ['product__code', 'key'],
                'unique_together': {('product', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.CharField(help_text="Internal edition identifier (e.g., 'ed-standard').", max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Edition code as appears in license payload (e.g., 'standard').", max_length=64)),
                ('name', models.CharField(help_text='Human-readable edition name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this edition.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this edition is currently offered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='products.product')),
            ],
            options={
                'ordering': ['product__code', 'code'],
                'unique_together': {('product', 'code')},
            },
        ),
    ]
